//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Ch11._11_1
{
    [TestFixture]
    public class _11_1_4Fixture : Test262Fixture
    {
        public _11_1_4Fixture()
            : base("ch11\\11.1\\11.1.4")
        {
        }

        [Test(Description = "elements elided at the end of an array do not contribute to its length")]
        public void _11_1_4_0()
        {
            RunFile("11.1.4-0.js");
        }

        [Test(Description = "Initialize array using ElementList (Elisionopt AssignmentExpression) when index property (read-only) exists in Array.prototype (step 5)")]
        public void _11_1_4_4_5_1()
        {
            RunFile("11.1.4_4-5-1.js");
        }

        [Test(Description = "Initialize array using ElementList (ElementList , Elisionopt AssignmentExpression) when index property (read-only) exists in Array.prototype (step 6)")]
        public void _11_1_4_5_6_1()
        {
            RunFile("11.1.4_5-6-1.js");
        }

        [Test(Description = "Checking various properties of the array defined with expression \"var array = []\"")]
        public void S11_1_4_A1_1()
        {
            RunFile("S11.1.4_A1.1.js");
        }

        [Test(Description = "Checking various properties the array defined with \"var array = [,,,,,]\"")]
        public void S11_1_4_A1_2()
        {
            RunFile("S11.1.4_A1.2.js");
        }

        [Test(Description = "Checking various properteis and contents of the array defined with \"var array = [1,2,3,4,5]\"")]
        public void S11_1_4_A1_3()
        {
            RunFile("S11.1.4_A1.3.js");
        }

        [Test(Description = "Checking various properteis and content of the array defined with \"var array = [,,,1,2]\"")]
        public void S11_1_4_A1_4()
        {
            RunFile("S11.1.4_A1.4.js");
        }

        [Test(Description = "Checking various properteis and contents of the array defined with \"var array = [4,5,,,,]\"")]
        public void S11_1_4_A1_5()
        {
            RunFile("S11.1.4_A1.5.js");
        }

        [Test(Description = "Checking various properteis and contents of the array defined with \"var array = [,,3,,,]\"")]
        public void S11_1_4_A1_6()
        {
            RunFile("S11.1.4_A1.6.js");
        }

        [Test(Description = "Checking various properteis and contents of the array defined with \"var array = [1,2,,4,5]\"")]
        public void S11_1_4_A1_7()
        {
            RunFile("S11.1.4_A1.7.js");
        }

        [Test(Description = "Checking various properteis and contents of the arrya defined with \"var array = [[1,2], [3], []]\"")]
        public void S11_1_4_A2()
        {
            RunFile("S11.1.4_A2.js");
        }
    }
}
