//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Ch12
{
    [TestFixture]
    public class _12_12Fixture : Test262Fixture
    {
        public _12_12Fixture()
            : base("ch12\\12.12")
        {
        }

        [Test(Description = "Checking if labelled break works. See continue and break sections")]
        public void S12_12_A1_T1()
        {
            RunFile("S12.12_A1_T1.js");
        }
    }
}
