//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Ch15._15_3._15_3_4
{
    [TestFixture]
    public class _15_3_4_2Fixture : Test262Fixture
    {
        public _15_3_4_2Fixture()
            : base("ch15\\15.3\\15.3.4\\15.3.4.2")
        {
        }

        [Test(Description = "Checking if varying the Function.prototype.toString.length property fails")]
        public void S15_3_4_2_A10()
        {
            RunFile("S15.3.4.2_A10.js");
        }

        [Test(Description = "Checking Function.prototype.toString.length")]
        public void S15_3_4_2_A11()
        {
            RunFile("S15.3.4.2_A11.js");
        }

        [Test(Description = "The Function.prototype.toString function is not generic; it throws a TypeError exception if its this value is not a Function object.")]
        [ExpectedException]
        public void S15_3_4_2_A12()
        {
            RunFile("S15.3.4.2_A12.js");
        }

        [Test(Description = "The toString function is not generic; it throws a TypeError exception if its this value is not a Function object.")]
        [ExpectedException]
        public void S15_3_4_2_A13()
        {
            RunFile("S15.3.4.2_A13.js");
        }

        [Test(Description = "The toString function is not generic; it throws a TypeError exception if its this value is not a Function object.")]
        [ExpectedException]
        public void S15_3_4_2_A14()
        {
            RunFile("S15.3.4.2_A14.js");
        }

        [Test(Description = "Whether or not they are callable, RegExp objects are not Function objects, so toString should throw a TypeError.")]
        [ExpectedException]
        public void S15_3_4_2_A15()
        {
            RunFile("S15.3.4.2_A15.js");
        }

        [Test(Description = "The String constructor, given an object, should invoke that object's toString method as a method, i.e., with its this value bound to that object.")]
        [ExpectedException]
        public void S15_3_4_2_A16()
        {
            RunFile("S15.3.4.2_A16.js");
        }

        [Test(Description = "Checking if obtaining the prototype property of Function.prototype.toString fails")]
        public void S15_3_4_2_A6()
        {
            RunFile("S15.3.4.2_A6.js");
        }

        [Test(Description = "Checking if creating \"new Function.prototype.toString\" fails")]
        public void S15_3_4_2_A7()
        {
            RunFile("S15.3.4.2_A7.js");
        }

        [Test(Description = "Checking if enumerating the Function.prototype.toString.length property fails")]
        public void S15_3_4_2_A8()
        {
            RunFile("S15.3.4.2_A8.js");
        }

        [Test(Description = "Checking if deleting the Function.prototype.toString.length property fails")]
        public void S15_3_4_2_A9()
        {
            RunFile("S15.3.4.2_A9.js");
        }
    }
}
