//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Ch15._15_3._15_3_4
{
    [TestFixture]
    public class _15_3_4_4Fixture : Test262Fixture
    {
        public _15_3_4_4Fixture()
            : base("ch15\\15.3\\15.3.4\\15.3.4.4")
        {
        }

        [Test(Description = "Strict Mode - 'this' value is a string which cannot be converted to wrapper objects when the function is called without an array of arguments")]
        public void _15_3_4_4_1_s()
        {
            RunFile("15.3.4.4-1-s.js");
        }

        [Test(Description = "Strict Mode - 'this' value is a number which cannot be converted to wrapper objects  when the function is called without an array argument")]
        public void _15_3_4_4_2_s()
        {
            RunFile("15.3.4.4-2-s.js");
        }

        [Test(Description = "Strict Mode - 'this' value is a boolean which cannot be converted to wrapper objects when the function is called without an array of arguments")]
        public void _15_3_4_4_3_s()
        {
            RunFile("15.3.4.4-3-s.js");
        }

        [Test(Description = "Checking if varying the Function.prototype.call.length property fails")]
        public void S15_3_4_4_A10()
        {
            RunFile("S15.3.4.4_A10.js");
        }

        [Test(Description = "Checking if enumerating the Function.prototype.call.length property fails")]
        public void S15_3_4_4_A11()
        {
            RunFile("S15.3.4.4_A11.js");
        }

        [Test(Description = "Checking if obtaining the prototype property of Function.prototype.call fails")]
        public void S15_3_4_4_A12()
        {
            RunFile("S15.3.4.4_A12.js");
        }

        [Test(Description = "If IsCallable(func) is false, then throw a TypeError exception.")]
        [ExpectedException]
        public void S15_3_4_4_A13()
        {
            RunFile("S15.3.4.4_A13.js");
        }

        [Test(Description = "If IsCallable(func) is false, then throw a TypeError exception.")]
        [ExpectedException]
        public void S15_3_4_4_A14()
        {
            RunFile("S15.3.4.4_A14.js");
        }

        [Test(Description = "If IsCallable(func) is false, then throw a TypeError exception.")]
        [ExpectedException]
        public void S15_3_4_4_A15()
        {
            RunFile("S15.3.4.4_A15.js");
        }

        [Test(Description = "A RegExp is not a function, but it may be callable. Iff it is, it's typeof should be 'function', in which case call should accept it as a valid this value.")]
        public void S15_3_4_4_A16()
        {
            RunFile("S15.3.4.4_A16.js");
        }

        [Test(Description = "Call \"call\" method of the object that does not have a [[Call]] property.")]
        public void S15_3_4_4_A1_T1()
        {
            RunFile("S15.3.4.4_A1_T1.js");
        }

        [Test(Description = "Calling \"call\" method of the object that does not have a [[Call]] property.")]
        public void S15_3_4_4_A1_T2()
        {
            RunFile("S15.3.4.4_A1_T2.js");
        }

        [Test(Description = "Checking Function.prototype.call.length")]
        public void S15_3_4_4_A2_T1()
        {
            RunFile("S15.3.4.4_A2_T1.js");
        }

        [Test(Description = "Checking f.call.length, where f is new Function")]
        public void S15_3_4_4_A2_T2()
        {
            RunFile("S15.3.4.4_A2_T2.js");
        }

        [Test(Description = "Not any arguments at call function")]
        public void S15_3_4_4_A3_T1()
        {
            RunFile("S15.3.4.4_A3_T1.js");
        }

        [Test(Description = "Checking by using eval, no any arguments at call function")]
        public void S15_3_4_4_A3_T10()
        {
            RunFile("S15.3.4.4_A3_T10.js");
        }

        [Test(Description = "Argument at call function is null")]
        public void S15_3_4_4_A3_T2()
        {
            RunFile("S15.3.4.4_A3_T2.js");
        }

        [Test(Description = "Argument at call function is void 0")]
        public void S15_3_4_4_A3_T3()
        {
            RunFile("S15.3.4.4_A3_T3.js");
        }

        [Test(Description = "Argument at call function is undefined")]
        public void S15_3_4_4_A3_T4()
        {
            RunFile("S15.3.4.4_A3_T4.js");
        }

        [Test(Description = "No any arguments at call function and it called inside function declaration")]
        public void S15_3_4_4_A3_T5()
        {
            RunFile("S15.3.4.4_A3_T5.js");
        }

        [Test(Description = "Argument at call function is null and it called inside function declaration")]
        public void S15_3_4_4_A3_T6()
        {
            RunFile("S15.3.4.4_A3_T6.js");
        }

        [Test(Description = "Argument at call function is void 0 and it called inside function declaration")]
        public void S15_3_4_4_A3_T7()
        {
            RunFile("S15.3.4.4_A3_T7.js");
        }

        [Test(Description = "Argument at call function is undefined and it called inside function declaration")]
        public void S15_3_4_4_A3_T8()
        {
            RunFile("S15.3.4.4_A3_T8.js");
        }

        [Test(Description = "Checking by using eval, argument at call function is void 0")]
        public void S15_3_4_4_A3_T9()
        {
            RunFile("S15.3.4.4_A3_T9.js");
        }

        [Test(Description = "thisArg is number")]
        public void S15_3_4_4_A5_T1()
        {
            RunFile("S15.3.4.4_A5_T1.js");
        }

        [Test(Description = "thisArg is boolean true")]
        public void S15_3_4_4_A5_T2()
        {
            RunFile("S15.3.4.4_A5_T2.js");
        }

        [Test(Description = "thisArg is string")]
        public void S15_3_4_4_A5_T3()
        {
            RunFile("S15.3.4.4_A5_T3.js");
        }

        [Test(Description = "thisArg is function variable that return this")]
        public void S15_3_4_4_A5_T4()
        {
            RunFile("S15.3.4.4_A5_T4.js");
        }

        [Test(Description = "thisArg is function variable")]
        public void S15_3_4_4_A5_T5()
        {
            RunFile("S15.3.4.4_A5_T5.js");
        }

        [Test(Description = "thisArg is new String()")]
        public void S15_3_4_4_A5_T6()
        {
            RunFile("S15.3.4.4_A5_T6.js");
        }

        [Test(Description = "thisArg is new Number()")]
        public void S15_3_4_4_A5_T7()
        {
            RunFile("S15.3.4.4_A5_T7.js");
        }

        [Test(Description = "thisArg is Function()")]
        public void S15_3_4_4_A5_T8()
        {
            RunFile("S15.3.4.4_A5_T8.js");
        }

        [Test(Description = "Argunemts of call function is (null,[1])")]
        public void S15_3_4_4_A6_T1()
        {
            RunFile("S15.3.4.4_A6_T1.js");
        }

        [Test(Description = "Argunemts of call function is (empty object, \"\", arguments,2), inside function call without declaration used")]
        public void S15_3_4_4_A6_T10()
        {
            RunFile("S15.3.4.4_A6_T10.js");
        }

        [Test(Description = "Argunemts of call function is (null,[3,2,1])")]
        public void S15_3_4_4_A6_T2()
        {
            RunFile("S15.3.4.4_A6_T2.js");
        }

        [Test(Description = "Argunemts of call function is (empty object, new Array(\"nine\",\"inch\",\"nails\"))")]
        public void S15_3_4_4_A6_T3()
        {
            RunFile("S15.3.4.4_A6_T3.js");
        }

        [Test(Description = "Argunemts of call function is (empty object, ( function(){return arguments;})(\"a\",\"b\",\"c\",\"d\"),\"\",2)")]
        public void S15_3_4_4_A6_T4()
        {
            RunFile("S15.3.4.4_A6_T4.js");
        }

        [Test(Description = "Argunemts of call function is (null, arguments,\"\",2), inside function declaration used")]
        public void S15_3_4_4_A6_T5()
        {
            RunFile("S15.3.4.4_A6_T5.js");
        }

        [Test(Description = "Argunemts of call function is (this, arguments,\"\",2), inside function declaration used")]
        public void S15_3_4_4_A6_T6()
        {
            RunFile("S15.3.4.4_A6_T6.js");
        }

        [Test(Description = "Argunemts of call function is (null, arguments,\"\",2), inside function call without declaration used")]
        public void S15_3_4_4_A6_T7()
        {
            RunFile("S15.3.4.4_A6_T7.js");
        }

        [Test(Description = "Argunemts of call function is (this, arguments,\"\",2), inside function call without declaration used")]
        public void S15_3_4_4_A6_T8()
        {
            RunFile("S15.3.4.4_A6_T8.js");
        }

        [Test(Description = "Argunemts of call function is (empty object, \"\", arguments,2), inside function declaration used")]
        public void S15_3_4_4_A6_T9()
        {
            RunFile("S15.3.4.4_A6_T9.js");
        }

        [Test(Description = "Checking if creating \"new Function.prototype.call\" fails")]
        public void S15_3_4_4_A7_T1()
        {
            RunFile("S15.3.4.4_A7_T1.js");
        }

        [Test(Description = "Checking if creating \"new Function.prototype.call()\" fails")]
        public void S15_3_4_4_A7_T2()
        {
            RunFile("S15.3.4.4_A7_T2.js");
        }

        [Test(Description = "Checking if creating \"new Function.call\" fails")]
        public void S15_3_4_4_A7_T3()
        {
            RunFile("S15.3.4.4_A7_T3.js");
        }

        [Test(Description = "Checking if creating \"new (Function(\"this.p1=1\").call)\" fails")]
        public void S15_3_4_4_A7_T4()
        {
            RunFile("S15.3.4.4_A7_T4.js");
        }

        [Test(Description = "Checking if creating \"new Function(\"this.p1=1\").call\" fails")]
        public void S15_3_4_4_A7_T5()
        {
            RunFile("S15.3.4.4_A7_T5.js");
        }

        [Test(Description = "Checking if creating \"new (Function(\"function f(){this.p1=1;};return f\").call())\" fails")]
        public void S15_3_4_4_A7_T6()
        {
            RunFile("S15.3.4.4_A7_T6.js");
        }

        [Test(Description = "Checking if deleting the Function.prototype.call.length property fails")]
        public void S15_3_4_4_A9()
        {
            RunFile("S15.3.4.4_A9.js");
        }
    }
}
