//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Intl402.Ch11
{
    [TestFixture]
    public class _11_1Fixture : Test262Fixture
    {
        public _11_1Fixture()
            : base("intl402\\ch11\\11.1")
        {
        }

        [Test(Description = "Tests that an object can't be re-initialized as a NumberFormat.")]
        public void _11_1_1_1()
        {
            RunFile("11.1.1_1.js");
        }

        [Test(Description = "Tests that the option style is processed correctly.")]
        public void _11_1_1_15()
        {
            RunFile("11.1.1_15.js");
        }

        [Test(Description = "Tests that the option currency is processed correctly.")]
        public void _11_1_1_17()
        {
            RunFile("11.1.1_17.js");
        }

        [Test(Description = "Tests that the currency style can not be used without a specified currency.")]
        public void _11_1_1_19()
        {
            RunFile("11.1.1_19.js");
        }

        [Test(Description = "Tests that the number of fractional digits is determined correctly for currencies.")]
        public void _11_1_1_20_c()
        {
            RunFile("11.1.1_20_c.js");
        }

        [Test(Description = "Tests that the option currencyDisplay is processed correctly.")]
        public void _11_1_1_21()
        {
            RunFile("11.1.1_21.js");
        }

        [Test(Description = "Tests that the options minimumSignificantDigits and")]
        public void _11_1_1_32()
        {
            RunFile("11.1.1_32.js");
        }

        [Test(Description = "Tests that the option useGrouping is processed correctly.")]
        public void _11_1_1_34()
        {
            RunFile("11.1.1_34.js");
        }

        [Test(Description = "Tests that the behavior of a Record is not affected by adversarial")]
        public void _11_1_1_6()
        {
            RunFile("11.1.1_6.js");
        }

        [Test(Description = "Tests that the option localeMatcher is processed correctly.")]
        public void _11_1_1_7()
        {
            RunFile("11.1.1_7.js");
        }

        [Test(Description = "Tests that constructing a NumberFormat doesn't create or modify")]
        public void _11_1_1_a()
        {
            RunFile("11.1.1_a.js");
        }

        [Test(Description = "Tests that for non-object values passed as this to NumberFormat a")]
        public void _11_1_2_1_4()
        {
            RunFile("11.1.2.1_4.js");
        }

        [Test(Description = "Tests that Intl.NumberFormat can be subclassed.")]
        public void _11_1_2()
        {
            RunFile("11.1.2.js");
        }

        [Test(Description = "Tests that objects constructed by Intl.NumberFormat have the specified internal properties.")]
        public void _11_1_3()
        {
            RunFile("11.1.3.js");
        }

        [Test(Description = "Tests that Intl.NumberFormat")]
        public void _11_1_L15()
        {
            RunFile("11.1_L15.js");
        }
    }
}
