//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Intl402.Ch11
{
    [TestFixture]
    public class _11_2Fixture : Test262Fixture
    {
        public _11_2Fixture()
            : base("intl402\\ch11\\11.2")
        {
        }

        [Test(Description = "Tests that Intl.NumberFormat.prototype has the required attributes.")]
        public void _11_2_1()
        {
            RunFile("11.2.1.js");
        }

        [Test(Description = "Tests that Intl.NumberFormat has a supportedLocalesOf")]
        public void _11_2_2_a()
        {
            RunFile("11.2.2_a.js");
        }

        [Test(Description = "Tests that Intl.NumberFormat.supportedLocalesOf")]
        public void _11_2_2_b()
        {
            RunFile("11.2.2_b.js");
        }

        [Test(Description = "Tests that Intl.NumberFormat.supportedLocalesOf")]
        public void _11_2_2_L15()
        {
            RunFile("11.2.2_L15.js");
        }

        [Test(Description = "Tests that Intl.NumberFormat does not accept Unicode locale")]
        public void _11_2_3_b()
        {
            RunFile("11.2.3_b.js");
        }
    }
}
