//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Ch15._15_2._15_2_3
{
    [TestFixture]
    public class _15_2_3_1Fixture : Test262Fixture
    {
        public _15_2_3_1Fixture()
            : base("ch15\\15.2\\15.2.3\\15.2.3.1")
        {
        }

        [Test(Description = "Object.prototype is a data property with default attribute values (false)")]
        public void _15_2_3_1()
        {
            RunFile("15.2.3.1.js");
        }

        [Test(Description = "Checking if varying \"Object.prototype\" property fails")]
        public void S15_2_3_1_A1()
        {
            RunFile("S15.2.3.1_A1.js");
        }

        [Test(Description = "Checking if enumerating \"Object.prototype\" property fails")]
        public void S15_2_3_1_A2()
        {
            RunFile("S15.2.3.1_A2.js");
        }

        [Test]
        public void S15_2_3_1_A3()
        {
            RunFile("S15.2.3.1_A3.js");
        }
    }
}
