//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Intl402.Ch13
{
    [TestFixture]
    public class _13_3Fixture : Test262Fixture
    {
        public _13_3Fixture()
            : base("intl402\\ch13\\13.3")
        {
        }

        [Test(Description = "Tests that Date.prototype.toLocaleString & Co. handle \"this time value\" correctly.")]
        public void _13_3_0_1()
        {
            RunFile("13.3.0_1.js");
        }

        [Test(Description = "Tests that Date.prototype.toLocaleString & Co. handle non-finite values correctly.")]
        public void _13_3_0_2()
        {
            RunFile("13.3.0_2.js");
        }

        [Test(Description = "Tests that Date.prototype.toLocaleString & Co. throws the same exceptions as Intl.DateTimeFormat.")]
        public void _13_3_0_6_1()
        {
            RunFile("13.3.0_6_1.js");
        }

        [Test(Description = "Tests that Date.prototype.toLocaleString & Co. use the standard")]
        public void _13_3_0_6_2()
        {
            RunFile("13.3.0_6_2.js");
        }

        [Test(Description = "Tests that Date.prototype.toLocaleString & Co. produces the same results as Intl.DateTimeFormat.")]
        public void _13_3_0_7()
        {
            RunFile("13.3.0_7.js");
        }

        [Test(Description = "Tests that Date.prototype.toLocaleString")]
        public void _13_3_1_L15()
        {
            RunFile("13.3.1_L15.js");
        }

        [Test(Description = "Tests that Date.prototype.toLocaleDateString")]
        public void _13_3_2_L15()
        {
            RunFile("13.3.2_L15.js");
        }

        [Test(Description = "Tests that Date.prototype.toLocaleTimeString")]
        public void _13_3_3_L15()
        {
            RunFile("13.3.3_L15.js");
        }
    }
}
