//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Ch15._15_10
{
    [TestFixture]
    public class _15_10_3Fixture : Test262Fixture
    {
        public _15_10_3Fixture()
            : base("ch15\\15.10\\15.10.3")
        {
        }

        [Test(Description = "R is /x/i and instance is RegExp(R)")]
        public void S15_10_3_1_A1_T1()
        {
            RunFile("S15.10.3.1_A1_T1.js");
        }

        [Test(Description = "R is new RegExp and instance is RegExp(R, function(){}())")]
        public void S15_10_3_1_A1_T2()
        {
            RunFile("S15.10.3.1_A1_T2.js");
        }

        [Test(Description = "R is new RegExp() and instance is RegExp(R, x), where x is undefined variable")]
        public void S15_10_3_1_A1_T3()
        {
            RunFile("S15.10.3.1_A1_T3.js");
        }

        [Test(Description = "R is new RegExp() and instance is RegExp(R, void 0)")]
        public void S15_10_3_1_A1_T4()
        {
            RunFile("S15.10.3.1_A1_T4.js");
        }

        [Test(Description = "R is /\\b/m and instance is RegExp(R, undefined)")]
        public void S15_10_3_1_A1_T5()
        {
            RunFile("S15.10.3.1_A1_T5.js");
        }

        [Test(Description = "Checking if using \"1\" as flags leads to throwing the correct exception")]
        public void S15_10_3_1_A2_T1()
        {
            RunFile("S15.10.3.1_A2_T1.js");
        }

        [Test(Description = "Checking if using dafined variable \"x = 1\" as flags leads to throwing the correct exception")]
        public void S15_10_3_1_A2_T2()
        {
            RunFile("S15.10.3.1_A2_T2.js");
        }

        [Test(Description = "R is \"d+\" and instance is RegExp(R,\"i\")")]
        public void S15_10_3_1_A3_T1()
        {
            RunFile("S15.10.3.1_A3_T1.js");
        }

        [Test(Description = "R is {toString:function(){return \"[a-c]*\";}} and instance is RegExp(R,\"gm\")")]
        public void S15_10_3_1_A3_T2()
        {
            RunFile("S15.10.3.1_A3_T2.js");
        }
    }
}
