//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Ch08._8_7
{
    [TestFixture]
    public class _8_7_2Fixture : Test262Fixture
    {
        public _8_7_2Fixture()
            : base("ch08\\8.7\\8.7.2")
        {
        }

        [Test(Description = "Strict Mode - ReferenceError is thrown if LeftHandSide evaluates to an unresolvable Reference")]
        public void _8_7_2_1_s()
        {
            RunFile("8.7.2-1-s.js");
        }

        [Test(Description = "Strict Mode - ReferenceError isn't thrown if LeftHandSide evaluates to a resolvable Reference")]
        public void _8_7_2_2_s()
        {
            RunFile("8.7.2-2-s.js");
        }

        [Test(Description = "eval - a property named 'eval' is permitted")]
        public void _8_7_2_3_1_s()
        {
            RunFile("8.7.2-3-1-s.js");
        }

        [Test(Description = "Strict Mode - ReferenceError is thrown if LeftHandSide evaluate to an unresolvable Reference")]
        [ExpectedException]
        public void _8_7_2_3_a_1gs()
        {
            RunFile("8.7.2-3-a-1gs.js");
        }

        [Test(Description = "Strict Mode - 'runtime' error is thrown before LeftHandSide evaluates to an unresolvable Reference")]
        [ExpectedException]
        public void _8_7_2_3_a_2gs()
        {
            RunFile("8.7.2-3-a-2gs.js");
        }

        [Test(Description = "Strict Mode - TypeError is thrown if LeftHandSide is a reference to a non-writable data property")]
        public void _8_7_2_3_s()
        {
            RunFile("8.7.2-3-s.js");
        }

        [Test(Description = "Strict Mode - TypeError is thrown if LeftHandSide is a reference to an accessor property with no setter")]
        public void _8_7_2_4_s()
        {
            RunFile("8.7.2-4-s.js");
        }

        [Test(Description = "Strict Mode - TypeError is thrown if LeftHandSide is a reference to a non-existent property of an non-extensible object")]
        public void _8_7_2_5_s()
        {
            RunFile("8.7.2-5-s.js");
        }

        [Test(Description = "Strict Mode - TypeError isn't thrown if LeftHandSide is a reference to a writable data property")]
        public void _8_7_2_6_s()
        {
            RunFile("8.7.2-6-s.js");
        }

        [Test(Description = "Strict Mode - TypeError isn't thrown if LeftHandSide is a reference to an accessor property with setter")]
        public void _8_7_2_7_s()
        {
            RunFile("8.7.2-7-s.js");
        }

        [Test(Description = "Strict Mode - TypeError isn't thrown if LeftHandSide is a reference to a property of an extensible object")]
        public void _8_7_2_8_s()
        {
            RunFile("8.7.2-8-s.js");
        }
    }
}
