//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Ch15._15_4._15_4_4
{
    [TestFixture]
    public class _15_4_4_6Fixture : Test262Fixture
    {
        public _15_4_4_6Fixture()
            : base("ch15\\15.4\\15.4.4\\15.4.4.6")
        {
        }

        [Test(Description = "Checking this algorithm")]
        public void S15_4_4_6_A1_1_T1()
        {
            RunFile("S15.4.4.6_A1.1_T1.js");
        }

        [Test(Description = "Checking this use new Array() and []")]
        public void S15_4_4_6_A1_2_T1()
        {
            RunFile("S15.4.4.6_A1.2_T1.js");
        }

        [Test(Description = "If ToUint32(length) equal zero, call the [[Put]] method")]
        public void S15_4_4_6_A2_T1()
        {
            RunFile("S15.4.4.6_A2_T1.js");
        }

        [Test(Description = "If ToUint32(length) equal zero, call the [[Put]] method")]
        public void S15_4_4_6_A2_T2()
        {
            RunFile("S15.4.4.6_A2_T2.js");
        }

        [Test(Description = "The last element ToUint32(length) - 1 of the array is removed from the array")]
        public void S15_4_4_6_A2_T3()
        {
            RunFile("S15.4.4.6_A2_T3.js");
        }

        [Test(Description = "Operator use ToNumber from length.")]
        public void S15_4_4_6_A2_T4()
        {
            RunFile("S15.4.4.6_A2_T4.js");
        }

        [Test(Description = "length = 4294967296")]
        public void S15_4_4_6_A3_T1()
        {
            RunFile("S15.4.4.6_A3_T1.js");
        }

        [Test(Description = "length = 4294967297")]
        public void S15_4_4_6_A3_T2()
        {
            RunFile("S15.4.4.6_A3_T2.js");
        }

        [Test(Description = "length = -1")]
        public void S15_4_4_6_A3_T3()
        {
            RunFile("S15.4.4.6_A3_T3.js");
        }

        [Test(Description = "[[Prototype]] of Array instance is Array.prototype, [[Prototype] of Array.prototype is Object.prototype")]
        public void S15_4_4_6_A4_T1()
        {
            RunFile("S15.4.4.6_A4_T1.js");
        }

        [Test(Description = "[[Prototype]] of Array instance is Array.prototype, [[Prototype] of Array.prototype is Object.prototype")]
        public void S15_4_4_6_A4_T2()
        {
            RunFile("S15.4.4.6_A4_T2.js");
        }

        [Test(Description = "Checking use propertyIsEnumerable, for-in")]
        public void S15_4_4_6_A5_1()
        {
            RunFile("S15.4.4.6_A5.1.js");
        }

        [Test(Description = "Checking use hasOwnProperty, delete")]
        public void S15_4_4_6_A5_2()
        {
            RunFile("S15.4.4.6_A5.2.js");
        }

        [Test(Description = "Checking if varying the length property fails")]
        public void S15_4_4_6_A5_3()
        {
            RunFile("S15.4.4.6_A5.3.js");
        }

        [Test(Description = "pop.length === 1")]
        public void S15_4_4_6_A5_4()
        {
            RunFile("S15.4.4.6_A5.4.js");
        }

        [Test(Description = "Checking use propertyIsEnumerable, for-in")]
        public void S15_4_4_6_A5_5()
        {
            RunFile("S15.4.4.6_A5.5.js");
        }

        [Test(Description = "Checking Array.prototype.pop.prototype")]
        public void S15_4_4_6_A5_6()
        {
            RunFile("S15.4.4.6_A5.6.js");
        }

        [Test(Description = "If property does not implement the internal [[Construct]] method, throw a TypeError exception")]
        public void S15_4_4_6_A5_7()
        {
            RunFile("S15.4.4.6_A5.7.js");
        }
    }
}
