//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Ch15._15_10._15_10_2
{
    [TestFixture]
    public class _15_10_2_5Fixture : Test262Fixture
    {
        public _15_10_2_5Fixture()
            : base("ch15\\15.10\\15.10.2\\15.10.2.5")
        {
        }

        [Test(Description = "Execute /a[a-z]{2,4}/.exec(\"abcdefghi\") and check results")]
        public void S15_10_2_5_A1_T1()
        {
            RunFile("S15.10.2.5_A1_T1.js");
        }

        [Test(Description = "Execute /a[a-z]{2,4}?/.exec(\"abcdefghi\") and check results")]
        public void S15_10_2_5_A1_T2()
        {
            RunFile("S15.10.2.5_A1_T2.js");
        }

        [Test(Description = "Execute /(aa|aabaac|ba|b|c)* /.exec(\"aabaac\") and check results")]
        public void S15_10_2_5_A1_T3()
        {
            RunFile("S15.10.2.5_A1_T3.js");
        }

        [Test(Description = "Execute /(z)((a+)?(b+)?(c))* /.exec(\"zaacbbbcac\") and check results")]
        public void S15_10_2_5_A1_T4()
        {
            RunFile("S15.10.2.5_A1_T4.js");
        }

        [Test(Description = "Execute /(a*)b\\1+/.exec(\"baaaac\") and check results")]
        public void S15_10_2_5_A1_T5()
        {
            RunFile("S15.10.2.5_A1_T5.js");
        }
    }
}
