//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Ch15._15_10._15_10_2
{
    [TestFixture]
    public class _15_10_2_9Fixture : Test262Fixture
    {
        public _15_10_2_9Fixture()
            : base("ch15\\15.10\\15.10.2\\15.10.2.9")
        {
        }

        [Test(Description = "Execute /\\b(\\w+) \\1\\b/.exec(\"do you listen the the band\") and check results")]
        public void S15_10_2_9_A1_T1()
        {
            RunFile("S15.10.2.9_A1_T1.js");
        }

        [Test(Description = "Execute /([xu]\\d{2}([A-H]{2})?)\\1/.exec(\"x09x12x01x01u00FFu00FFx04x04x23\") and check results")]
        public void S15_10_2_9_A1_T2()
        {
            RunFile("S15.10.2.9_A1_T2.js");
        }

        [Test(Description = "Execute /([xu]\\d{2}([A-H]{2})?)\\1/.exec(\"x09x12x01x05u00FFu00FFx04x04x23\") and check results")]
        public void S15_10_2_9_A1_T3()
        {
            RunFile("S15.10.2.9_A1_T3.js");
        }

        [Test(Description = "Execute /\\b(\\w+) \\2\\b/.test(\"do you listen the the band\") and check results")]
        public void S15_10_2_9_A1_T4()
        {
            RunFile("S15.10.2.9_A1_T4.js");
        }

        [Test(Description = "Execute /(a*)b\\1+/.exec(\"baaac\") and check results")]
        public void S15_10_2_9_A1_T5()
        {
            RunFile("S15.10.2.9_A1_T5.js");
        }
    }
}
