//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Ch15._15_5._15_5_5
{
    [TestFixture]
    public class _15_5_5_2Fixture : Test262Fixture
    {
        public _15_5_5_2Fixture()
            : base("ch15\\15.5\\15.5.5\\15.5.5.2")
        {
        }

        [Test(Description = "String object supports bracket notation to lookup of data properties")]
        public void _15_5_5_5_2_1_1()
        {
            RunFile("15.5.5.5.2-1-1.js");
        }

        [Test(Description = "String value supports bracket notation to lookup data properties")]
        public void _15_5_5_5_2_1_2()
        {
            RunFile("15.5.5.5.2-1-2.js");
        }

        [Test(Description = "String object indexing returns undefined for missing data properties")]
        public void _15_5_5_5_2_3_1()
        {
            RunFile("15.5.5.5.2-3-1.js");
        }

        [Test(Description = "String value indexing returns undefined for missing data properties")]
        public void _15_5_5_5_2_3_2()
        {
            RunFile("15.5.5.5.2-3-2.js");
        }

        [Test(Description = "String object indexing returns undefined if the numeric index (NaN) is not an array index")]
        public void _15_5_5_5_2_3_3()
        {
            RunFile("15.5.5.5.2-3-3.js");
        }

        [Test(Description = "String object indexing returns undefined if the numeric index (Infinity) is not an array index")]
        public void _15_5_5_5_2_3_4()
        {
            RunFile("15.5.5.5.2-3-4.js");
        }

        [Test(Description = "String object indexing returns undefined if the numeric index ( 2^32-1) is not an array index")]
        public void _15_5_5_5_2_3_5()
        {
            RunFile("15.5.5.5.2-3-5.js");
        }

        [Test(Description = "String value indexing returns undefined if the numeric index (NaN) is not an array index")]
        public void _15_5_5_5_2_3_6()
        {
            RunFile("15.5.5.5.2-3-6.js");
        }

        [Test(Description = "String value indexing returns undefined if the numeric index (Infinity) is not an array index")]
        public void _15_5_5_5_2_3_7()
        {
            RunFile("15.5.5.5.2-3-7.js");
        }

        [Test(Description = "String value indexing returns undefined if the numeric index ( >= 2^32-1) is not an array index")]
        public void _15_5_5_5_2_3_8()
        {
            RunFile("15.5.5.5.2-3-8.js");
        }

        [Test(Description = "String object indexing returns undefined if the numeric index is less than 0")]
        public void _15_5_5_5_2_7_1()
        {
            RunFile("15.5.5.5.2-7-1.js");
        }

        [Test(Description = "String value indexing returns undefined if the numeric index is less than 0")]
        public void _15_5_5_5_2_7_2()
        {
            RunFile("15.5.5.5.2-7-2.js");
        }

        [Test(Description = "String object indexing returns undefined if the numeric index is greater than the string length")]
        public void _15_5_5_5_2_7_3()
        {
            RunFile("15.5.5.5.2-7-3.js");
        }

        [Test(Description = "String value indexing returns undefined if the numeric index is greater than the string length")]
        public void _15_5_5_5_2_7_4()
        {
            RunFile("15.5.5.5.2-7-4.js");
        }
    }
}
