//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Ch15._15_5._15_5_4
{
    [TestFixture]
    public class _15_5_4_9Fixture : Test262Fixture
    {
        public _15_5_4_9Fixture()
            : base("ch15\\15.5\\15.5.4\\15.5.4.9")
        {
        }

        [Test(Description = "Tests that String.prototype.localeCompare treats a missing")]
        public void _15_5_4_9_3()
        {
            RunFile("15.5.4.9_3.js");
        }

        [Test(Description = "Tests that String.prototype.localeCompare")]
        public void _15_5_4_9_CE()
        {
            RunFile("15.5.4.9_CE.js");
        }

        [Test(Description = "Checking if varying the String.prototype.localeCompare.length property fails")]
        public void S15_5_4_9_A10()
        {
            RunFile("S15.5.4.9_A10.js");
        }

        [Test(Description = "Checking String.prototype.localeCompare.length")]
        public void S15_5_4_9_A11()
        {
            RunFile("S15.5.4.9_A11.js");
        }

        [Test(Description = "This string is symbol and arguments are symbols")]
        public void S15_5_4_9_A1_T1()
        {
            RunFile("S15.5.4.9_A1_T1.js");
        }

        [Test(Description = "Call string_1.localeCompare(string_2) is equal -string_2.localeCompare(string_1)")]
        public void S15_5_4_9_A1_T2()
        {
            RunFile("S15.5.4.9_A1_T2.js");
        }

        [Test(Description = "Checking String.prototype.localeCompare.prototype")]
        public void S15_5_4_9_A6()
        {
            RunFile("S15.5.4.9_A6.js");
        }

        [Test(Description = "Checking if creating the String.prototype.localeCompare object fails")]
        public void S15_5_4_9_A7()
        {
            RunFile("S15.5.4.9_A7.js");
        }

        [Test(Description = "Checking if enumerating the String.prototype.localeCompare.length property fails")]
        public void S15_5_4_9_A8()
        {
            RunFile("S15.5.4.9_A8.js");
        }

        [Test(Description = "Checking if deleting the String.prototype.localeCompare.length property fails")]
        public void S15_5_4_9_A9()
        {
            RunFile("S15.5.4.9_A9.js");
        }
    }
}
