//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Ch15._15_8._15_8_1
{
    [TestFixture]
    public class _15_8_1_3Fixture : Test262Fixture
    {
        public _15_8_1_3Fixture()
            : base("ch15\\15.8\\15.8.1\\15.8.1.3")
        {
        }

        [Test(Description = "Comparing Math.LN2 with 0.6931471805599453")]
        public void S15_8_1_3_A1()
        {
            RunFile("S15.8.1.3_A1.js");
        }

        [Test(Description = "Checking if Math.LN2 property has the attribute DontEnum")]
        public void S15_8_1_3_A2()
        {
            RunFile("S15.8.1.3_A2.js");
        }

        [Test(Description = "Checking if Math.LN2 property has the attribute DontDelete")]
        public void S15_8_1_3_A3()
        {
            RunFile("S15.8.1.3_A3.js");
        }

        [Test(Description = "Checking if Math.LN2 property has the attribute DontDelete")]
        public void S15_8_1_3_A4()
        {
            RunFile("S15.8.1.3_A4.js");
        }
    }
}
