//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Intl402.Ch09
{
    [TestFixture]
    public class _9_2Fixture : Test262Fixture
    {
        public _9_2Fixture()
            : base("intl402\\ch09\\9.2")
        {
        }

        [Test(Description = "Tests that canonicalization of locale lists treats undefined and empty lists the same.")]
        public void _9_2_1_1()
        {
            RunFile("9.2.1_1.js");
        }

        [Test(Description = "Tests that the behavior of a List is not affected by adversarial")]
        public void _9_2_1_2()
        {
            RunFile("9.2.1_2.js");
        }

        [Test(Description = "Tests that a single string instead of a locale list is treated")]
        public void _9_2_1_3()
        {
            RunFile("9.2.1_3.js");
        }

        [Test(Description = "Tests that non-objects are converted to objects before canonicalization.")]
        public void _9_2_1_4()
        {
            RunFile("9.2.1_4.js");
        }

        [Test(Description = "Tests that values other than strings are not accepted as locales.")]
        public void _9_2_1_8_c_ii()
        {
            RunFile("9.2.1_8_c_ii.js");
        }

        [Test(Description = "Tests that canonicalization of locale lists removes duplicate language tags.")]
        public void _9_2_1_8_c_vi()
        {
            RunFile("9.2.1_8_c_vi.js");
        }

        [Test(Description = "Tests that locales that are reported by resolvedOptions")]
        public void _9_2_2()
        {
            RunFile("9.2.2.js");
        }

        [Test(Description = "Tests that the behavior of a Record is not affected by adversarial")]
        public void _9_2_3_5()
        {
            RunFile("9.2.3_5.js");
        }

        [Test(Description = "Tests that missing Unicode extension values default to true for")]
        public void _9_2_5_11_g_ii_2()
        {
            RunFile("9.2.5_11_g_ii_2.js");
        }

        [Test(Description = "Tests that the behavior of a Record is not affected by adversarial")]
        public void _9_2_5_6()
        {
            RunFile("9.2.5_6.js");
        }

        [Test(Description = "Tests that the behavior of a List is not affected by adversarial")]
        public void _9_2_6_2()
        {
            RunFile("9.2.6_2.js");
        }

        [Test(Description = "Tests that LookupSupportedLocales returns an empty list when")]
        public void _9_2_6_4()
        {
            RunFile("9.2.6_4.js");
        }

        [Test(Description = "Tests that Unicode locale extension sequences do not affect")]
        public void _9_2_6_4_b()
        {
            RunFile("9.2.6_4_b.js");
        }

        [Test(Description = "Tests that LookupSupportedLocales includes the default locale")]
        public void _9_2_6_4_c()
        {
            RunFile("9.2.6_4_c.js");
        }

        [Test(Description = "Tests that the option localeMatcher is processed correctly.")]
        public void _9_2_8_1_c()
        {
            RunFile("9.2.8_1_c.js");
        }

        [Test(Description = "Tests that the array returned by SupportedLocales is extensible,")]
        public void _9_2_8_4()
        {
            RunFile("9.2.8_4.js");
        }
    }
}
