//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Intl402.Ch10
{
    [TestFixture]
    public class _10_3Fixture : Test262Fixture
    {
        public _10_3Fixture()
            : base("intl402\\ch10\\10.3")
        {
        }

        [Test(Description = "Tests that Intl.Collator.prototype.constructor is the")]
        public void _10_3_1()
        {
            RunFile("10.3.1.js");
        }

        [Test(Description = "Tests that the function returned by Intl.Collator.prototype.compare")]
        public void _10_3_2_1_a_L15()
        {
            RunFile("10.3.2_1_a_L15.js");
        }

        [Test(Description = "Tests that compare function is bound to its Intl.Collator.")]
        public void _10_3_2_1_c()
        {
            RunFile("10.3.2_1_c.js");
        }

        [Test(Description = "Tests that the function returned by Intl.Collator.prototype.compare")]
        public void _10_3_2_CS_a()
        {
            RunFile("10.3.2_CS_a.js");
        }

        [Test(Description = "Tests that the compare function isn't entirely unreasonable.")]
        public void _10_3_2_CS_b_NN()
        {
            RunFile("10.3.2_CS_b_NN.js");
        }

        [Test(Description = "Tests that the compare function supports phonebook sorting if it says it does.")]
        public void _10_3_2_CS_c_NN()
        {
            RunFile("10.3.2_CS_c_NN.js");
        }

        [Test(Description = "Tests that the compare function supports different sensitivity settings.")]
        public void _10_3_2_CS_d_NN()
        {
            RunFile("10.3.2_CS_d_NN.js");
        }

        [Test(Description = "Tests that the getter for Intl.Collator.prototype.compare")]
        public void _10_3_2_L15()
        {
            RunFile("10.3.2_L15.js");
        }

        [Test(Description = "Tests that the object returned by Intl.Collator.prototype.resolvedOptions")]
        public void _10_3_3()
        {
            RunFile("10.3.3.js");
        }

        [Test(Description = "Tests that Intl.Collator.prototype.resolvedOptions")]
        public void _10_3_3_L15()
        {
            RunFile("10.3.3_L15.js");
        }

        [Test(Description = "Tests that Intl.Collator.prototype is an object that")]
        public void _10_3_a()
        {
            RunFile("10.3_a.js");
        }

        [Test(Description = "Tests that Intl.Collator.prototype functions throw a")]
        public void _10_3_b()
        {
            RunFile("10.3_b.js");
        }

        [Test(Description = "Tests that Intl.Collator.prototype")]
        public void _10_3_L15()
        {
            RunFile("10.3_L15.js");
        }
    }
}
