//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Ch15._15_11._15_11_4
{
    [TestFixture]
    public class _15_11_4_3Fixture : Test262Fixture
    {
        public _15_11_4_3Fixture()
            : base("ch15\\15.11\\15.11.4\\15.11.4.3")
        {
        }

        [Test(Description = "Error.prototype.message is not enumerable.")]
        public void _15_11_4_3_1()
        {
            RunFile("15.11.4.3-1.js");
        }
    }
}
