//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Ch15._15_11._15_11_4
{
    [TestFixture]
    public class _15_11_4_4Fixture : Test262Fixture
    {
        public _15_11_4_4Fixture()
            : base("ch15\\15.11\\15.11.4\\15.11.4.4")
        {
        }

        [Test(Description = "Error.prototype.toString return the result of concatenating 'name', ':', a single space character, and 'msg' when 'name' and 'msg' are non-empty string")]
        public void _15_11_4_4_10_1()
        {
            RunFile("15.11.4.4-10-1.js");
        }

        [Test(Description = "Error.prototype.toString - 'Error' is returned when 'name' is absent and empty string is returned when 'msg' is undefined")]
        public void _15_11_4_4_6_1()
        {
            RunFile("15.11.4.4-6-1.js");
        }

        [Test(Description = "Error.prototype.toString - 'Error' is returned when 'name' is absent and value of 'msg' is returned when 'msg' is non-empty string")]
        public void _15_11_4_4_6_2()
        {
            RunFile("15.11.4.4-6-2.js");
        }

        [Test(Description = "Error.prototype.toString return the value of 'msg' when 'name' is empty string and 'msg' isn't undefined")]
        public void _15_11_4_4_8_1()
        {
            RunFile("15.11.4.4-8-1.js");
        }

        [Test(Description = "Error.prototype.toString return empty string when 'name' is empty string and 'msg' is undefined")]
        public void _15_11_4_4_8_2()
        {
            RunFile("15.11.4.4-8-2.js");
        }

        [Test(Description = "Error.prototype.toString return 'name' when 'name' is non-empty string and 'msg' is empty string")]
        public void _15_11_4_4_9_1()
        {
            RunFile("15.11.4.4-9-1.js");
        }
    }
}
