//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Ch15._15_3._15_3_5
{
    [TestFixture]
    public class _15_3_5_4Fixture : Test262Fixture
    {
        public _15_3_5_4Fixture()
            : base("ch15\\15.3\\15.3.5\\15.3.5.4")
        {
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (New'ed Function constructor includes strict directive prologue)")]
        [ExpectedException]
        public void _15_3_5_4_2_10gs()
        {
            RunFile("15.3.5.4_2-10gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from strict function (eval used within strict mode)")]
        [ExpectedException]
        public void _15_3_5_4_2_11gs()
        {
            RunFile("15.3.5.4_2-11gs.js");
        }

        [Test(Description = "Strict mode - checking access to non-strict function caller from non-strict function (eval includes strict directive prologue)")]
        public void _15_3_5_4_2_12gs()
        {
            RunFile("15.3.5.4_2-12gs.js");
        }

        [Test(Description = "Strict mode - checking access to non-strict function caller from strict function (indirect eval used within strict mode)")]
        [ExpectedException]
        public void _15_3_5_4_2_13gs()
        {
            RunFile("15.3.5.4_2-13gs.js");
        }

        [Test(Description = "Strict mode - checking access to non-strict function caller from non-strict function (indirect eval includes strict directive prologue)")]
        public void _15_3_5_4_2_14gs()
        {
            RunFile("15.3.5.4_2-14gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from strict function (New'ed object from FunctionDeclaration defined within strict mode)")]
        [ExpectedException]
        public void _15_3_5_4_2_15gs()
        {
            RunFile("15.3.5.4_2-15gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (New'ed object from FunctionDeclaration includes strict directive prologue)")]
        [ExpectedException]
        public void _15_3_5_4_2_16gs()
        {
            RunFile("15.3.5.4_2-16gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from strict function (New'ed object from FunctionExpression defined within strict mode)")]
        [ExpectedException]
        public void _15_3_5_4_2_17gs()
        {
            RunFile("15.3.5.4_2-17gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (New'ed object from FunctionExpression includes strict directive prologue)")]
        [ExpectedException]
        public void _15_3_5_4_2_18gs()
        {
            RunFile("15.3.5.4_2-18gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from strict function (New'ed object from Anonymous FunctionExpression defined within strict mode)")]
        [ExpectedException]
        public void _15_3_5_4_2_19gs()
        {
            RunFile("15.3.5.4_2-19gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from strict function (FunctionDeclaration defined within strict mode)")]
        [ExpectedException]
        public void _15_3_5_4_2_1gs()
        {
            RunFile("15.3.5.4_2-1gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (New'ed object from Anonymous FunctionExpression includes strict directive prologue)")]
        [ExpectedException]
        public void _15_3_5_4_2_20gs()
        {
            RunFile("15.3.5.4_2-20gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from strict function (FunctionDeclaration defined within a FunctionDeclaration inside strict mode)")]
        [ExpectedException]
        public void _15_3_5_4_2_21gs()
        {
            RunFile("15.3.5.4_2-21gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from strict function (FunctionExpression defined within a FunctionDeclaration inside strict mode)")]
        [ExpectedException]
        public void _15_3_5_4_2_22gs()
        {
            RunFile("15.3.5.4_2-22gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from strict function (Anonymous FunctionExpression defined within a FunctionDeclaration inside strict mode)")]
        [ExpectedException]
        public void _15_3_5_4_2_23gs()
        {
            RunFile("15.3.5.4_2-23gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from strict function (FunctionDeclaration defined within a FunctionExpression inside strict mode)")]
        [ExpectedException]
        public void _15_3_5_4_2_24gs()
        {
            RunFile("15.3.5.4_2-24gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from strict function (FunctionExpression defined within a FunctionExpression inside strict mode)")]
        [ExpectedException]
        public void _15_3_5_4_2_25gs()
        {
            RunFile("15.3.5.4_2-25gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from strict function (Anonymous FunctionExpression defined within a FunctionExpression inside strict mode)")]
        [ExpectedException]
        public void _15_3_5_4_2_26gs()
        {
            RunFile("15.3.5.4_2-26gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from strict function (FunctionDeclaration defined within an Anonymous FunctionExpression inside strict mode)")]
        [ExpectedException]
        public void _15_3_5_4_2_27gs()
        {
            RunFile("15.3.5.4_2-27gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from strict function (FunctionExpression defined within an Anonymous FunctionExpression inside strict mode)")]
        [ExpectedException]
        public void _15_3_5_4_2_28gs()
        {
            RunFile("15.3.5.4_2-28gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from strict function (Anonymous FunctionExpression defined within an Anonymous FunctionExpression inside strict mode)")]
        [ExpectedException]
        public void _15_3_5_4_2_29gs()
        {
            RunFile("15.3.5.4_2-29gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (FunctionDeclaration includes strict directive prologue)")]
        [ExpectedException]
        public void _15_3_5_4_2_2gs()
        {
            RunFile("15.3.5.4_2-2gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (FunctionDeclaration defined within a FunctionDeclaration with a strict directive prologue)")]
        [ExpectedException]
        public void _15_3_5_4_2_30gs()
        {
            RunFile("15.3.5.4_2-30gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (FunctionExpression defined within a FunctionDeclaration with a strict directive prologue)")]
        [ExpectedException]
        public void _15_3_5_4_2_31gs()
        {
            RunFile("15.3.5.4_2-31gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (Anonymous FunctionExpression defined within a FunctionDeclaration with a strict directive prologue)")]
        [ExpectedException]
        public void _15_3_5_4_2_32gs()
        {
            RunFile("15.3.5.4_2-32gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (FunctionDeclaration defined within a FunctionExpression with a strict directive prologue)")]
        [ExpectedException]
        public void _15_3_5_4_2_33gs()
        {
            RunFile("15.3.5.4_2-33gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (FunctionExpression defined within a FunctionExpression with a strict directive prologue)")]
        [ExpectedException]
        public void _15_3_5_4_2_34gs()
        {
            RunFile("15.3.5.4_2-34gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (Anonymous FunctionExpression defined within a FunctionExpression with a strict directive prologue)")]
        [ExpectedException]
        public void _15_3_5_4_2_35gs()
        {
            RunFile("15.3.5.4_2-35gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (FunctionDeclaration defined within an Anonymous FunctionExpression with a strict directive prologue)")]
        [ExpectedException]
        public void _15_3_5_4_2_36gs()
        {
            RunFile("15.3.5.4_2-36gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (FunctionExpression defined within an Anonymous FunctionExpression with a strict directive prologue)")]
        [ExpectedException]
        public void _15_3_5_4_2_37gs()
        {
            RunFile("15.3.5.4_2-37gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (Anonymous FunctionExpression defined within an Anonymous FunctionExpression with a strict directive prologue)")]
        [ExpectedException]
        public void _15_3_5_4_2_38gs()
        {
            RunFile("15.3.5.4_2-38gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (FunctionDeclaration with a strict directive prologue defined within a FunctionDeclaration)")]
        [ExpectedException]
        public void _15_3_5_4_2_39gs()
        {
            RunFile("15.3.5.4_2-39gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from strict function (FunctionExpression defined within strict mode)")]
        [ExpectedException]
        public void _15_3_5_4_2_3gs()
        {
            RunFile("15.3.5.4_2-3gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (FunctionExpression with a strict directive prologue defined within a FunctionDeclaration)")]
        [ExpectedException]
        public void _15_3_5_4_2_40gs()
        {
            RunFile("15.3.5.4_2-40gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (Anonymous FunctionExpression with a strict directive prologue defined within a FunctionDeclaration)")]
        [ExpectedException]
        public void _15_3_5_4_2_41gs()
        {
            RunFile("15.3.5.4_2-41gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (FunctionDeclaration with a strict directive prologue defined within a FunctionExpression)")]
        [ExpectedException]
        public void _15_3_5_4_2_42gs()
        {
            RunFile("15.3.5.4_2-42gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (FunctionExpression with a strict directive prologue defined within a FunctionExpression)")]
        [ExpectedException]
        public void _15_3_5_4_2_43gs()
        {
            RunFile("15.3.5.4_2-43gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (Anonymous FunctionExpression with a strict directive prologue defined within a FunctionExpression)")]
        [ExpectedException]
        public void _15_3_5_4_2_44gs()
        {
            RunFile("15.3.5.4_2-44gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (FunctionDeclaration with a strict directive prologue defined within an Anonymous FunctionExpression)")]
        [ExpectedException]
        public void _15_3_5_4_2_45gs()
        {
            RunFile("15.3.5.4_2-45gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (FunctionExpression with a strict directive prologue defined within an Anonymous FunctionExpression)")]
        [ExpectedException]
        public void _15_3_5_4_2_46gs()
        {
            RunFile("15.3.5.4_2-46gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (Anonymous FunctionExpression with a strict directive prologue defined within an Anonymous FunctionExpression)")]
        [ExpectedException]
        public void _15_3_5_4_2_47gs()
        {
            RunFile("15.3.5.4_2-47gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from strict function (Literal getter defined within strict mode)")]
        [ExpectedException]
        public void _15_3_5_4_2_48gs()
        {
            RunFile("15.3.5.4_2-48gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (Literal getter includes strict directive prologue)")]
        [ExpectedException]
        public void _15_3_5_4_2_49gs()
        {
            RunFile("15.3.5.4_2-49gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (FunctionExpression includes strict directive prologue)")]
        [ExpectedException]
        public void _15_3_5_4_2_4gs()
        {
            RunFile("15.3.5.4_2-4gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from strict function (Literal setter defined within strict mode)")]
        [ExpectedException]
        public void _15_3_5_4_2_50gs()
        {
            RunFile("15.3.5.4_2-50gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (Literal setter includes strict directive prologue)")]
        [ExpectedException]
        public void _15_3_5_4_2_51gs()
        {
            RunFile("15.3.5.4_2-51gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from strict function (Injected getter defined within strict mode)")]
        [ExpectedException]
        public void _15_3_5_4_2_52gs()
        {
            RunFile("15.3.5.4_2-52gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (Injected getter includes strict directive prologue)")]
        [ExpectedException]
        public void _15_3_5_4_2_53gs()
        {
            RunFile("15.3.5.4_2-53gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from strict function (Injected setter defined within strict mode)")]
        [ExpectedException]
        public void _15_3_5_4_2_54gs()
        {
            RunFile("15.3.5.4_2-54gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (Injected setter includes strict directive prologue)")]
        [ExpectedException]
        public void _15_3_5_4_2_55gs()
        {
            RunFile("15.3.5.4_2-55gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (strict function declaration called by non-strict function declaration)")]
        [ExpectedException]
        public void _15_3_5_4_2_56gs()
        {
            RunFile("15.3.5.4_2-56gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (strict function declaration called by non-strict eval)")]
        [ExpectedException]
        public void _15_3_5_4_2_57gs()
        {
            RunFile("15.3.5.4_2-57gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (strict function declaration called by non-strict Function constructor)")]
        [ExpectedException]
        public void _15_3_5_4_2_58gs()
        {
            RunFile("15.3.5.4_2-58gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (strict function declaration called by non-strict new'ed Function constructor)")]
        [ExpectedException]
        public void _15_3_5_4_2_59gs()
        {
            RunFile("15.3.5.4_2-59gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from strict function (Anonymous FunctionExpression defined within strict mode)")]
        [ExpectedException]
        public void _15_3_5_4_2_5gs()
        {
            RunFile("15.3.5.4_2-5gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (strict function declaration called by Function.prototype.apply())")]
        [ExpectedException]
        public void _15_3_5_4_2_60gs()
        {
            RunFile("15.3.5.4_2-60gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (strict function declaration called by Function.prototype.apply(null))")]
        [ExpectedException]
        public void _15_3_5_4_2_61gs()
        {
            RunFile("15.3.5.4_2-61gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (strict function declaration called by Function.prototype.apply(undefined))")]
        [ExpectedException]
        public void _15_3_5_4_2_62gs()
        {
            RunFile("15.3.5.4_2-62gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (strict function declaration called by Function.prototype.apply(someObject))")]
        [ExpectedException]
        public void _15_3_5_4_2_63gs()
        {
            RunFile("15.3.5.4_2-63gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (strict function declaration called by Function.prototype.apply(globalObject))")]
        [ExpectedException]
        public void _15_3_5_4_2_64gs()
        {
            RunFile("15.3.5.4_2-64gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (strict function declaration called by Function.prototype.call())")]
        [ExpectedException]
        public void _15_3_5_4_2_65gs()
        {
            RunFile("15.3.5.4_2-65gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (strict function declaration called by Function.prototype.call(null))")]
        [ExpectedException]
        public void _15_3_5_4_2_66gs()
        {
            RunFile("15.3.5.4_2-66gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (strict function declaration called by Function.prototype.call(undefined))")]
        [ExpectedException]
        public void _15_3_5_4_2_67gs()
        {
            RunFile("15.3.5.4_2-67gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (strict function declaration called by Function.prototype.call(someObject))")]
        [ExpectedException]
        public void _15_3_5_4_2_68gs()
        {
            RunFile("15.3.5.4_2-68gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (strict function declaration called by Function.prototype.call(globalObject))")]
        [ExpectedException]
        public void _15_3_5_4_2_69gs()
        {
            RunFile("15.3.5.4_2-69gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (Anonymous FunctionExpression includes strict directive prologue)")]
        [ExpectedException]
        public void _15_3_5_4_2_6gs()
        {
            RunFile("15.3.5.4_2-6gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (strict function declaration called by Function.prototype.bind()())")]
        [ExpectedException]
        public void _15_3_5_4_2_70gs()
        {
            RunFile("15.3.5.4_2-70gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (strict function declaration called by Function.prototype.bind(null)())")]
        [ExpectedException]
        public void _15_3_5_4_2_71gs()
        {
            RunFile("15.3.5.4_2-71gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (strict function declaration called by Function.prototype.bind(undefined)())")]
        [ExpectedException]
        public void _15_3_5_4_2_72gs()
        {
            RunFile("15.3.5.4_2-72gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (strict function declaration called by Function.prototype.bind(someObject)())")]
        [ExpectedException]
        public void _15_3_5_4_2_73gs()
        {
            RunFile("15.3.5.4_2-73gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (strict function declaration called by Function.prototype.bind(globalObject)())")]
        [ExpectedException]
        public void _15_3_5_4_2_74gs()
        {
            RunFile("15.3.5.4_2-74gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (non-strict function declaration called by strict function declaration)")]
        public void _15_3_5_4_2_75gs()
        {
            RunFile("15.3.5.4_2-75gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (non-strict function declaration called by strict eval)")]
        public void _15_3_5_4_2_76gs()
        {
            RunFile("15.3.5.4_2-76gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (non-strict function declaration called by strict Function constructor)")]
        public void _15_3_5_4_2_77gs()
        {
            RunFile("15.3.5.4_2-77gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (non-strict function declaration called by strict new'ed Function constructor)")]
        public void _15_3_5_4_2_78gs()
        {
            RunFile("15.3.5.4_2-78gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (non-strict function declaration called by strict Function.prototype.apply())")]
        public void _15_3_5_4_2_79gs()
        {
            RunFile("15.3.5.4_2-79gs.js");
        }

        [Test(Description = "Strict mode - checking access to non-strict function caller from strict function (Function constructor defined within strict mode)")]
        [ExpectedException]
        public void _15_3_5_4_2_7gs()
        {
            RunFile("15.3.5.4_2-7gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (non-strict function declaration called by strict Function.prototype.apply(null))")]
        public void _15_3_5_4_2_80gs()
        {
            RunFile("15.3.5.4_2-80gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (non-strict function declaration called by strict Function.prototype.apply(undefined))")]
        public void _15_3_5_4_2_81gs()
        {
            RunFile("15.3.5.4_2-81gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (non-strict function declaration called by strict Function.prototype.apply(someObject))")]
        public void _15_3_5_4_2_82gs()
        {
            RunFile("15.3.5.4_2-82gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (non-strict function declaration called by strict Function.prototype.apply(globalObject))")]
        public void _15_3_5_4_2_83gs()
        {
            RunFile("15.3.5.4_2-83gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (non-strict function declaration called by strict Function.prototype.call())")]
        public void _15_3_5_4_2_84gs()
        {
            RunFile("15.3.5.4_2-84gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (non-strict function declaration called by strict Function.prototype.call(null))")]
        public void _15_3_5_4_2_85gs()
        {
            RunFile("15.3.5.4_2-85gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (non-strict function declaration called by strict Function.prototype.call(undefined))")]
        public void _15_3_5_4_2_86gs()
        {
            RunFile("15.3.5.4_2-86gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (non-strict function declaration called by strict Function.prototype.call(someObject))")]
        public void _15_3_5_4_2_87gs()
        {
            RunFile("15.3.5.4_2-87gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (non-strict function declaration called by strict Function.prototype.call(globalObject))")]
        public void _15_3_5_4_2_88gs()
        {
            RunFile("15.3.5.4_2-88gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (non-strict function declaration called by strict Function.prototype.bind()())")]
        public void _15_3_5_4_2_89gs()
        {
            RunFile("15.3.5.4_2-89gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (Function constructor includes strict directive prologue)")]
        [ExpectedException]
        public void _15_3_5_4_2_8gs()
        {
            RunFile("15.3.5.4_2-8gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (non-strict function declaration called by strict Function.prototype.bind(null)())")]
        public void _15_3_5_4_2_90gs()
        {
            RunFile("15.3.5.4_2-90gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (non-strict function declaration called by strict Function.prototype.bind(undefined)())")]
        public void _15_3_5_4_2_91gs()
        {
            RunFile("15.3.5.4_2-91gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (non-strict function declaration called by strict Function.prototype.bind(someObject)())")]
        public void _15_3_5_4_2_92gs()
        {
            RunFile("15.3.5.4_2-92gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function (non-strict function declaration called by strict Function.prototype.bind(globalObject)())")]
        public void _15_3_5_4_2_93gs()
        {
            RunFile("15.3.5.4_2-93gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict function expression (FunctionDeclaration includes strict directive prologue)")]
        [ExpectedException]
        public void _15_3_5_4_2_94gs()
        {
            RunFile("15.3.5.4_2-94gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict, constructor-based function (FunctionDeclaration includes strict directive prologue)")]
        [ExpectedException]
        public void _15_3_5_4_2_95gs()
        {
            RunFile("15.3.5.4_2-95gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from non-strict property (FunctionDeclaration includes strict directive prologue)")]
        [ExpectedException]
        public void _15_3_5_4_2_96gs()
        {
            RunFile("15.3.5.4_2-96gs.js");
        }

        [Test(Description = "Strict mode - checking access to strict function caller from bound non-strict function (FunctionDeclaration includes strict directive prologue)")]
        [ExpectedException]
        public void _15_3_5_4_2_97gs()
        {
            RunFile("15.3.5.4_2-97gs.js");
        }

        [Test(Description = "Strict mode - checking access to non-strict function caller from strict function (New'ed Function constructor defined within strict mode)")]
        [ExpectedException]
        public void _15_3_5_4_2_9gs()
        {
            RunFile("15.3.5.4_2-9gs.js");
        }
    }
}
