//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Ch15
{
    [TestFixture]
    public class _15_1Fixture : Test262Fixture
    {
        public _15_1Fixture()
            : base("ch15\\15.1")
        {
        }

        [Test(Description = "It is not possible to use the global object as a constructor")]
        [ExpectedException]
        public void S15_1_A1_T1()
        {
            RunFile("S15.1_A1_T1.js");
        }

        [Test(Description = "It is not possible to use the global object as a constructor")]
        [ExpectedException]
        public void S15_1_A1_T2()
        {
            RunFile("S15.1_A1_T2.js");
        }

        [Test(Description = "It is not possible to invoke the global object as a function")]
        [ExpectedException]
        public void S15_1_A2_T1()
        {
            RunFile("S15.1_A2_T1.js");
        }
    }
}
