//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Ch15
{
    [TestFixture]
    public class _15_11Fixture : Test262Fixture
    {
        public _15_11Fixture()
            : base("ch15\\15.11")
        {
        }

        [Test(Description = "Error - ConversionError has been removed from IE9 standard mode")]
        public void _15_11_1()
        {
            RunFile("15.11-1.js");
        }

        [Test(Description = "Error - RegExpError has been removed from IE9 standard mode")]
        public void _15_11_2()
        {
            RunFile("15.11-2.js");
        }
    }
}
