//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Ch15._15_7._15_7_4
{
    [TestFixture]
    public class _15_7_4_2Fixture : Test262Fixture
    {
        public _15_7_4_2Fixture()
            : base("ch15\\15.7\\15.7.4\\15.7.4.2")
        {
        }

        [Test(Description = "undefined radix")]
        public void S15_7_4_2_A1_T01()
        {
            RunFile("S15.7.4.2_A1_T01.js");
        }

        [Test(Description = "radix is 10")]
        public void S15_7_4_2_A1_T02()
        {
            RunFile("S15.7.4.2_A1_T02.js");
        }

        [Test(Description = "radix is undefined value")]
        public void S15_7_4_2_A1_T03()
        {
            RunFile("S15.7.4.2_A1_T03.js");
        }

        [Test(Description = "radix is 2")]
        public void S15_7_4_2_A2_T01()
        {
            RunFile("S15.7.4.2_A2_T01.js");
        }

        [Test(Description = "radix is 3")]
        public void S15_7_4_2_A2_T02()
        {
            RunFile("S15.7.4.2_A2_T02.js");
        }

        [Test(Description = "radix is 4")]
        public void S15_7_4_2_A2_T03()
        {
            RunFile("S15.7.4.2_A2_T03.js");
        }

        [Test(Description = "radix is 5")]
        public void S15_7_4_2_A2_T04()
        {
            RunFile("S15.7.4.2_A2_T04.js");
        }

        [Test(Description = "radix is 6")]
        public void S15_7_4_2_A2_T05()
        {
            RunFile("S15.7.4.2_A2_T05.js");
        }

        [Test(Description = "radix is 7")]
        public void S15_7_4_2_A2_T06()
        {
            RunFile("S15.7.4.2_A2_T06.js");
        }

        [Test(Description = "radix is 8")]
        public void S15_7_4_2_A2_T07()
        {
            RunFile("S15.7.4.2_A2_T07.js");
        }

        [Test(Description = "radix is 9")]
        public void S15_7_4_2_A2_T08()
        {
            RunFile("S15.7.4.2_A2_T08.js");
        }

        [Test(Description = "radix is 11")]
        public void S15_7_4_2_A2_T09()
        {
            RunFile("S15.7.4.2_A2_T09.js");
        }

        [Test(Description = "radix is 12")]
        public void S15_7_4_2_A2_T10()
        {
            RunFile("S15.7.4.2_A2_T10.js");
        }

        [Test(Description = "radix is 13")]
        public void S15_7_4_2_A2_T11()
        {
            RunFile("S15.7.4.2_A2_T11.js");
        }

        [Test(Description = "radix is 14")]
        public void S15_7_4_2_A2_T12()
        {
            RunFile("S15.7.4.2_A2_T12.js");
        }

        [Test(Description = "radix is 15")]
        public void S15_7_4_2_A2_T13()
        {
            RunFile("S15.7.4.2_A2_T13.js");
        }

        [Test(Description = "radix is 16")]
        public void S15_7_4_2_A2_T14()
        {
            RunFile("S15.7.4.2_A2_T14.js");
        }

        [Test(Description = "radix is 17")]
        public void S15_7_4_2_A2_T15()
        {
            RunFile("S15.7.4.2_A2_T15.js");
        }

        [Test(Description = "radix is 18")]
        public void S15_7_4_2_A2_T16()
        {
            RunFile("S15.7.4.2_A2_T16.js");
        }

        [Test(Description = "radix is 19")]
        public void S15_7_4_2_A2_T17()
        {
            RunFile("S15.7.4.2_A2_T17.js");
        }

        [Test(Description = "radix is 20")]
        public void S15_7_4_2_A2_T18()
        {
            RunFile("S15.7.4.2_A2_T18.js");
        }

        [Test(Description = "radix is 21")]
        public void S15_7_4_2_A2_T19()
        {
            RunFile("S15.7.4.2_A2_T19.js");
        }

        [Test(Description = "radix is 22")]
        public void S15_7_4_2_A2_T20()
        {
            RunFile("S15.7.4.2_A2_T20.js");
        }

        [Test(Description = "radix is 23")]
        public void S15_7_4_2_A2_T21()
        {
            RunFile("S15.7.4.2_A2_T21.js");
        }

        [Test(Description = "radix is 24")]
        public void S15_7_4_2_A2_T22()
        {
            RunFile("S15.7.4.2_A2_T22.js");
        }

        [Test(Description = "radix is 25")]
        public void S15_7_4_2_A2_T23()
        {
            RunFile("S15.7.4.2_A2_T23.js");
        }

        [Test(Description = "radix is 26")]
        public void S15_7_4_2_A2_T24()
        {
            RunFile("S15.7.4.2_A2_T24.js");
        }

        [Test(Description = "radix is 27")]
        public void S15_7_4_2_A2_T25()
        {
            RunFile("S15.7.4.2_A2_T25.js");
        }

        [Test(Description = "radix is 28")]
        public void S15_7_4_2_A2_T26()
        {
            RunFile("S15.7.4.2_A2_T26.js");
        }

        [Test(Description = "radix is 29")]
        public void S15_7_4_2_A2_T27()
        {
            RunFile("S15.7.4.2_A2_T27.js");
        }

        [Test(Description = "radix is 30")]
        public void S15_7_4_2_A2_T28()
        {
            RunFile("S15.7.4.2_A2_T28.js");
        }

        [Test(Description = "radix is 31")]
        public void S15_7_4_2_A2_T29()
        {
            RunFile("S15.7.4.2_A2_T29.js");
        }

        [Test(Description = "radix is 32")]
        public void S15_7_4_2_A2_T30()
        {
            RunFile("S15.7.4.2_A2_T30.js");
        }

        [Test(Description = "radix is 33")]
        public void S15_7_4_2_A2_T31()
        {
            RunFile("S15.7.4.2_A2_T31.js");
        }

        [Test(Description = "radix is 34")]
        public void S15_7_4_2_A2_T32()
        {
            RunFile("S15.7.4.2_A2_T32.js");
        }

        [Test(Description = "radix is 35")]
        public void S15_7_4_2_A2_T33()
        {
            RunFile("S15.7.4.2_A2_T33.js");
        }

        [Test(Description = "radix is 36")]
        public void S15_7_4_2_A2_T34()
        {
            RunFile("S15.7.4.2_A2_T34.js");
        }

        [Test(Description = "radix is 1")]
        public void S15_7_4_2_A3_T01()
        {
            RunFile("S15.7.4.2_A3_T01.js");
        }

        [Test(Description = "radix is 37")]
        public void S15_7_4_2_A3_T02()
        {
            RunFile("S15.7.4.2_A3_T02.js");
        }

        [Test(Description = "radix is null value")]
        public void S15_7_4_2_A3_T03()
        {
            RunFile("S15.7.4.2_A3_T03.js");
        }

        [Test(Description = "radix is 0")]
        public void S15_7_4_2_A3_T04()
        {
            RunFile("S15.7.4.2_A3_T04.js");
        }

        [Test(Description = "transferring to the String objects")]
        public void S15_7_4_2_A4_T01()
        {
            RunFile("S15.7.4.2_A4_T01.js");
        }

        [Test(Description = "transferring to the Boolean objects")]
        public void S15_7_4_2_A4_T02()
        {
            RunFile("S15.7.4.2_A4_T02.js");
        }

        [Test(Description = "transferring to the Date objects")]
        public void S15_7_4_2_A4_T03()
        {
            RunFile("S15.7.4.2_A4_T03.js");
        }

        [Test(Description = "transferring to the Object objects")]
        public void S15_7_4_2_A4_T04()
        {
            RunFile("S15.7.4.2_A4_T04.js");
        }

        [Test(Description = "transferring to the other objects")]
        public void S15_7_4_2_A4_T05()
        {
            RunFile("S15.7.4.2_A4_T05.js");
        }
    }
}
