//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Ch15._15_7._15_7_4
{
    [TestFixture]
    public class _15_7_4_4Fixture : Test262Fixture
    {
        public _15_7_4_4Fixture()
            : base("ch15\\15.7\\15.7.4\\15.7.4.4")
        {
        }

        [Test(Description = "Call without argument")]
        public void S15_7_4_4_A1_T01()
        {
            RunFile("S15.7.4.4_A1_T01.js");
        }

        [Test(Description = "calling with argument")]
        public void S15_7_4_4_A1_T02()
        {
            RunFile("S15.7.4.4_A1_T02.js");
        }

        [Test(Description = "transferring to the String objects")]
        public void S15_7_4_4_A2_T01()
        {
            RunFile("S15.7.4.4_A2_T01.js");
        }

        [Test(Description = "transferring to the Boolean objects")]
        public void S15_7_4_4_A2_T02()
        {
            RunFile("S15.7.4.4_A2_T02.js");
        }

        [Test(Description = "transferring to the Date objects")]
        public void S15_7_4_4_A2_T03()
        {
            RunFile("S15.7.4.4_A2_T03.js");
        }

        [Test(Description = "transferring to the Object objects")]
        public void S15_7_4_4_A2_T04()
        {
            RunFile("S15.7.4.4_A2_T04.js");
        }

        [Test(Description = "transferring to the other objects")]
        public void S15_7_4_4_A2_T05()
        {
            RunFile("S15.7.4.4_A2_T05.js");
        }
    }
}
