//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Ch15._15_7._15_7_3
{
    [TestFixture]
    public class _15_7_3_1Fixture : Test262Fixture
    {
        public _15_7_3_1Fixture()
            : base("ch15\\15.7\\15.7.3\\15.7.3.1")
        {
        }

        [Test(Description = "Number.prototype is a data property with default attribute values (false)")]
        public void _15_7_3_1_1()
        {
            RunFile("15.7.3.1-1.js");
        }

        [Test(Description = "Number.prototype, initial value is the Number prototype object")]
        public void _15_7_3_1_2()
        {
            RunFile("15.7.3.1-2.js");
        }

        [Test(Description = "Checking if varying the Number.prototype property fails")]
        public void S15_7_3_1_A1_T1()
        {
            RunFile("S15.7.3.1_A1_T1.js");
        }

        [Test(Description = "Checking if deleting the Number.prototype property fails")]
        public void S15_7_3_1_A1_T2()
        {
            RunFile("S15.7.3.1_A1_T2.js");
        }

        [Test(Description = "Checking if enumerating the Number.prototype property fails")]
        public void S15_7_3_1_A1_T3()
        {
            RunFile("S15.7.3.1_A1_T3.js");
        }

        [Test(Description = "Checking type of Number.prototype property - test based on")]
        public void S15_7_3_1_A2_T1()
        {
            RunFile("S15.7.3.1_A2_T1.js");
        }

        [Test(Description = "Checking type of Number.prototype property - test based on")]
        public void S15_7_3_1_A2_T2()
        {
            RunFile("S15.7.3.1_A2_T2.js");
        }

        [Test(Description = "Checking value of Number.prototype property")]
        public void S15_7_3_1_A3()
        {
            RunFile("S15.7.3.1_A3.js");
        }
    }
}
