//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Ch15._15_1._15_1_1
{
    [TestFixture]
    public class _15_1_1_2Fixture : Test262Fixture
    {
        public _15_1_1_2Fixture()
            : base("ch15\\15.1\\15.1.1\\15.1.1.2")
        {
        }

        [Test(Description = "Global.Infinity is a data property with default attribute values (false)")]
        public void _15_1_1_2_0()
        {
            RunFile("15.1.1.2-0.js");
        }

        [Test(Description = "Use typeof, isNaN, isFinite")]
        public void S15_1_1_2_A1()
        {
            RunFile("S15.1.1.2_A1.js");
        }

        [Test(Description = "Checking typeof Functions")]
        public void S15_1_1_2_A2_T2()
        {
            RunFile("S15.1.1.2_A2_T2.js");
        }

        [Test(Description = "Use delete")]
        public void S15_1_1_2_A3_1()
        {
            RunFile("S15.1.1.2_A3.1.js");
        }

        [Test(Description = "Use for-in statement")]
        public void S15_1_1_2_A3_2()
        {
            RunFile("S15.1.1.2_A3.2.js");
        }
    }
}
