//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Ch15._15_5
{
    [TestFixture]
    public class _15_5_1Fixture : Test262Fixture
    {
        public _15_5_1Fixture()
            : base("ch15\\15.5\\15.5.1")
        {
        }

        [Test(Description = "Call String(function(){}())")]
        public void S15_5_1_1_A1_T1()
        {
            RunFile("S15.5.1.1_A1_T1.js");
        }

        [Test(Description = "Call String(1) and String(-1)")]
        public void S15_5_1_1_A1_T10()
        {
            RunFile("S15.5.1.1_A1_T10.js");
        }

        [Test(Description = "Call String(1/0) and String(-1/0), and call with +/-Infinity")]
        public void S15_5_1_1_A1_T11()
        {
            RunFile("S15.5.1.1_A1_T11.js");
        }

        [Test(Description = "Call String(1/\"a\"), String(\"b\"* null) and String(Number.NaN)")]
        public void S15_5_1_1_A1_T12()
        {
            RunFile("S15.5.1.1_A1_T12.js");
        }

        [Test(Description = "Call String(true) and String(false)")]
        public void S15_5_1_1_A1_T13()
        {
            RunFile("S15.5.1.1_A1_T13.js");
        }

        [Test(Description = "Call String(0) and String(-0)")]
        public void S15_5_1_1_A1_T14()
        {
            RunFile("S15.5.1.1_A1_T14.js");
        }

        [Test(Description = "Call String(string_object)")]
        public void S15_5_1_1_A1_T15()
        {
            RunFile("S15.5.1.1_A1_T15.js");
        }

        [Test(Description = "Call String() with .12345 and analogous numbers")]
        public void S15_5_1_1_A1_T16()
        {
            RunFile("S15.5.1.1_A1_T16.js");
        }

        [Test(Description = "Call String() with numbers that have more than 1 significant digit after point")]
        public void S15_5_1_1_A1_T17()
        {
            RunFile("S15.5.1.1_A1_T17.js");
        }

        [Test(Description = "Call String() with numbers that have more than 1 significant digit")]
        public void S15_5_1_1_A1_T18()
        {
            RunFile("S15.5.1.1_A1_T18.js");
        }

        [Test(Description = "Call String() with Array of numbers")]
        public void S15_5_1_1_A1_T19()
        {
            RunFile("S15.5.1.1_A1_T19.js");
        }

        [Test(Description = "Call String(null)")]
        public void S15_5_1_1_A1_T2()
        {
            RunFile("S15.5.1.1_A1_T2.js");
        }

        [Test(Description = "Call String(void 0)")]
        public void S15_5_1_1_A1_T3()
        {
            RunFile("S15.5.1.1_A1_T3.js");
        }

        [Test(Description = "Call String(undefined)")]
        public void S15_5_1_1_A1_T4()
        {
            RunFile("S15.5.1.1_A1_T4.js");
        }

        [Test(Description = "Call String(x), where x is undefined variable")]
        public void S15_5_1_1_A1_T5()
        {
            RunFile("S15.5.1.1_A1_T5.js");
        }

        [Test(Description = "Checking by using eval, Call String(eval());")]
        public void S15_5_1_1_A1_T6()
        {
            RunFile("S15.5.1.1_A1_T6.js");
        }

        [Test(Description = "Call String({})")]
        public void S15_5_1_1_A1_T7()
        {
            RunFile("S15.5.1.1_A1_T7.js");
        }

        [Test(Description = "Call String(new Array)")]
        public void S15_5_1_1_A1_T8()
        {
            RunFile("S15.5.1.1_A1_T8.js");
        }

        [Test(Description = "Call String(this)")]
        public void S15_5_1_1_A1_T9()
        {
            RunFile("S15.5.1.1_A1_T9.js");
        }

        [Test(Description = "Call String()")]
        public void S15_5_1_1_A2_T1()
        {
            RunFile("S15.5.1.1_A2_T1.js");
        }
    }
}
