//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Intl402.Ch08
{
    [TestFixture]
    public class _8_0Fixture : Test262Fixture
    {
        public _8_0Fixture()
            : base("intl402\\ch08\\8.0")
        {
        }

        [Test(Description = "Tests that Intl has Object.prototype as its prototype.")]
        public void _8_0()
        {
            RunFile("8.0.js");
        }

        [Test(Description = "Tests that Intl")]
        public void _8_0_L15()
        {
            RunFile("8.0_L15.js");
        }
    }
}
