//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Ch15._15_3
{
    [TestFixture]
    public class _15_3_5Fixture : Test262Fixture
    {
        public _15_3_5Fixture()
            : base("ch15\\15.3\\15.3.5")
        {
        }

        [Test(Description = "StrictMode - error is thrown when reading the 'caller' property of a function object")]
        [ExpectedException]
        public void _15_3_5_1gs()
        {
            RunFile("15.3.5-1gs.js");
        }

        [Test(Description = "StrictMode - error is thrown when reading the 'caller' property of a function object")]
        [ExpectedException]
        public void _15_3_5_2gs()
        {
            RunFile("15.3.5-2gs.js");
        }

        [Test(Description = "Checking length property of Function(\"arg1,arg2,arg3\", null)")]
        public void S15_3_5_1_A1_T1()
        {
            RunFile("S15.3.5.1_A1_T1.js");
        }

        [Test(Description = "Checking length property of Function(\"arg1,arg2,arg3\",\"arg4,arg5\", null)")]
        public void S15_3_5_1_A1_T2()
        {
            RunFile("S15.3.5.1_A1_T2.js");
        }

        [Test(Description = "Checking length property of Function(\"arg1,arg2,arg3\",\"arg1,arg2\",\"arg3\", null)")]
        public void S15_3_5_1_A1_T3()
        {
            RunFile("S15.3.5.1_A1_T3.js");
        }

        [Test(Description = "Checking if deleting the length property of Function(\"arg1,arg2,arg3\", null) fails")]
        public void S15_3_5_1_A2_T1()
        {
            RunFile("S15.3.5.1_A2_T1.js");
        }

        [Test(Description = "Checking if deleting the length property of Function(\"arg1,arg2,arg3\",\"arg4,arg5\", null) fails")]
        public void S15_3_5_1_A2_T2()
        {
            RunFile("S15.3.5.1_A2_T2.js");
        }

        [Test(Description = "Checking if deleting the length property of Function(\"arg1,arg2,arg3\",\"arg1,arg2\",\"arg3\", null) fails")]
        public void S15_3_5_1_A2_T3()
        {
            RunFile("S15.3.5.1_A2_T3.js");
        }

        [Test(Description = "Checking if varying the length property of Function(\"arg1,arg2,arg3\",\"arg4,arg5\", null) fails")]
        public void S15_3_5_1_A3_T1()
        {
            RunFile("S15.3.5.1_A3_T1.js");
        }

        [Test(Description = "Checking if varying the length property of Function(\"arg1,arg2,arg3\", null) fails")]
        public void S15_3_5_1_A3_T2()
        {
            RunFile("S15.3.5.1_A3_T2.js");
        }

        [Test(Description = "Checking if varying the length property of Function(\"arg1,arg2,arg3\",\"arg1,arg2\",\"arg3\", null) fails")]
        public void S15_3_5_1_A3_T3()
        {
            RunFile("S15.3.5.1_A3_T3.js");
        }

        [Test(Description = "Checking if enumerating the length property of Function(\"arg1,arg2,arg3\", null) fails")]
        public void S15_3_5_1_A4_T1()
        {
            RunFile("S15.3.5.1_A4_T1.js");
        }

        [Test(Description = "Checking if enumerating the length property of Function(\"arg1,arg2,arg3\",\"arg4,arg5\", null) fails")]
        public void S15_3_5_1_A4_T2()
        {
            RunFile("S15.3.5.1_A4_T2.js");
        }

        [Test(Description = "Checking if enumerating the length property of Function(\"arg1,arg2,arg3\",\"arg1,arg2\",\"arg3\", null) fails")]
        public void S15_3_5_1_A4_T3()
        {
            RunFile("S15.3.5.1_A4_T3.js");
        }

        [Test(Description = "Checking if deleting the prototype property of Function(\"\", null) fails")]
        public void S15_3_5_2_A1_T1()
        {
            RunFile("S15.3.5.2_A1_T1.js");
        }

        [Test(Description = "Checking if deleting the prototype property of Function(void 0, \"\") fails")]
        public void S15_3_5_2_A1_T2()
        {
            RunFile("S15.3.5.2_A1_T2.js");
        }

        [Test(Description = "V is number")]
        public void S15_3_5_3_A1_T1()
        {
            RunFile("S15.3.5.3_A1_T1.js");
        }

        [Test(Description = "V is string")]
        public void S15_3_5_3_A1_T2()
        {
            RunFile("S15.3.5.3_A1_T2.js");
        }

        [Test(Description = "V is boolean true")]
        public void S15_3_5_3_A1_T3()
        {
            RunFile("S15.3.5.3_A1_T3.js");
        }

        [Test(Description = "V is boolean false")]
        public void S15_3_5_3_A1_T4()
        {
            RunFile("S15.3.5.3_A1_T4.js");
        }

        [Test(Description = "V is void 0")]
        public void S15_3_5_3_A1_T5()
        {
            RunFile("S15.3.5.3_A1_T5.js");
        }

        [Test(Description = "V is null")]
        public void S15_3_5_3_A1_T6()
        {
            RunFile("S15.3.5.3_A1_T6.js");
        }

        [Test(Description = "V is undefined")]
        public void S15_3_5_3_A1_T7()
        {
            RunFile("S15.3.5.3_A1_T7.js");
        }

        [Test(Description = "V is undefined variable")]
        public void S15_3_5_3_A1_T8()
        {
            RunFile("S15.3.5.3_A1_T8.js");
        }

        [Test(Description = "F.prototype is undefined, and V is empty object")]
        public void S15_3_5_3_A2_T2()
        {
            RunFile("S15.3.5.3_A2_T2.js");
        }

        [Test(Description = "F.prototype is void 0, and V is new F")]
        public void S15_3_5_3_A2_T5()
        {
            RunFile("S15.3.5.3_A2_T5.js");
        }

        [Test(Description = "F.prototype is string, and V is function")]
        public void S15_3_5_3_A2_T6()
        {
            RunFile("S15.3.5.3_A2_T6.js");
        }

        [Test(Description = "F.prototype.type is 1, and V is new F")]
        public void S15_3_5_3_A3_T1()
        {
            RunFile("S15.3.5.3_A3_T1.js");
        }

        [Test(Description = "F.prototype is Object.prototype, and V is empty object")]
        public void S15_3_5_3_A3_T2()
        {
            RunFile("S15.3.5.3_A3_T2.js");
        }

        [Test(Description = "For testing use variable f = new Function")]
        public void S15_3_5_A1_T1()
        {
            RunFile("S15.3.5_A1_T1.js");
        }

        [Test(Description = "For testing use variable f = Function()")]
        public void S15_3_5_A1_T2()
        {
            RunFile("S15.3.5_A1_T2.js");
        }

        [Test(Description = "For testing call Function(\"var x =1; this.y=2;return \\\"OK\\\";\")()")]
        public void S15_3_5_A2_T1()
        {
            RunFile("S15.3.5_A2_T1.js");
        }

        [Test(Description = "For testing call (new Function(\"arg1,arg2\",\"var x =arg1; this.y=arg2;return arg1+arg2;\"))(\"1\",2)")]
        public void S15_3_5_A2_T2()
        {
            RunFile("S15.3.5_A2_T2.js");
        }

        [Test(Description = "As constructor use Function(\"var x =1; this.y=2;return \\\"OK\\\";\")")]
        public void S15_3_5_A3_T1()
        {
            RunFile("S15.3.5_A3_T1.js");
        }

        [Test(Description = "As constructor use new Function(\"arg1,arg2\",\"var x =1; this.y=arg1+arg2;return \\\"OK\\\";\")")]
        public void S15_3_5_A3_T2()
        {
            RunFile("S15.3.5_A3_T2.js");
        }
    }
}
