//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Ch15._15_8._15_8_2
{
    [TestFixture]
    public class _15_8_2_1Fixture : Test262Fixture
    {
        public _15_8_2_1Fixture()
            : base("ch15\\15.8\\15.8.2\\15.8.2.1")
        {
        }

        [Test(Description = "Checking if Math.abs(NaN) is NaN")]
        public void S15_8_2_1_A1()
        {
            RunFile("S15.8.2.1_A1.js");
        }

        [Test(Description = "Checking if Math.abs(-0) equals to +0")]
        public void S15_8_2_1_A2()
        {
            RunFile("S15.8.2.1_A2.js");
        }

        [Test(Description = "Checking if Math.abs(-Infinity) equals to +Infinity")]
        public void S15_8_2_1_A3()
        {
            RunFile("S15.8.2.1_A3.js");
        }
    }
}
