//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Ch15._15_8._15_8_2
{
    [TestFixture]
    public class _15_8_2_2Fixture : Test262Fixture
    {
        public _15_8_2_2Fixture()
            : base("ch15\\15.8\\15.8.2\\15.8.2.2")
        {
        }

        [Test(Description = "Checking if Math.acos(NaN) is NaN")]
        public void S15_8_2_2_A1()
        {
            RunFile("S15.8.2.2_A1.js");
        }

        [Test(Description = "Checking if Math.acos(x) is NaN, where x is greater than 1")]
        public void S15_8_2_2_A2()
        {
            RunFile("S15.8.2.2_A2.js");
        }

        [Test(Description = "Checking if Math.acos(x) is NaN, where x is less than -1")]
        public void S15_8_2_2_A3()
        {
            RunFile("S15.8.2.2_A3.js");
        }

        [Test(Description = "Checking if Math.acos(1) equals to +0")]
        public void S15_8_2_2_A4()
        {
            RunFile("S15.8.2.2_A4.js");
        }

        [Test(Description = "Checking if Math.acos is approximately equals to its mathematical values on the set of 64 argument values; all the sample values is calculated with LibC")]
        public void S15_8_2_2_A5()
        {
            RunFile("S15.8.2.2_A5.js");
        }
    }
}
