//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Ch15._15_2._15_2_4
{
    [TestFixture]
    public class _15_2_4_3Fixture : Test262Fixture
    {
        public _15_2_4_3Fixture()
            : base("ch15\\15.2\\15.2.4\\15.2.4.3")
        {
        }

        [Test(Description = "Checking the type of Object.prototype.toLocaleString and the returned result")]
        public void S15_2_4_3_A1()
        {
            RunFile("S15.2.4.3_A1.js");
        }

        [Test(Description = "Checking if varying the Object.prototype.toLocaleString.length property fails")]
        public void S15_2_4_3_A10()
        {
            RunFile("S15.2.4.3_A10.js");
        }

        [Test(Description = "Checking the Object.prototype.toLocaleString.length")]
        public void S15_2_4_3_A11()
        {
            RunFile("S15.2.4.3_A11.js");
        }

        [Test(Description = "Let O be the result of calling ToObject passing the this value as the argument.")]
        [ExpectedException]
        public void S15_2_4_3_A12()
        {
            RunFile("S15.2.4.3_A12.js");
        }

        [Test(Description = "Let O be the result of calling ToObject passing the this value as the argument.")]
        [ExpectedException]
        public void S15_2_4_3_A13()
        {
            RunFile("S15.2.4.3_A13.js");
        }

        [Test(Description = "Checking if obtaining the prototype property of Object.prototype.toLocaleString fails")]
        public void S15_2_4_3_A6()
        {
            RunFile("S15.2.4.3_A6.js");
        }

        [Test(Description = "Checking if creating \"new Object.prototype.toLocaleString\" fails")]
        public void S15_2_4_3_A7()
        {
            RunFile("S15.2.4.3_A7.js");
        }

        [Test(Description = "Checking if enumerating the Object.prototype.toLocaleString.length property fails")]
        public void S15_2_4_3_A8()
        {
            RunFile("S15.2.4.3_A8.js");
        }

        [Test(Description = "Checknig if deleting of the Object.prototype.toLocaleString.length property fails")]
        public void S15_2_4_3_A9()
        {
            RunFile("S15.2.4.3_A9.js");
        }
    }
}
