//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Ch15._15_10._15_10_7
{
    [TestFixture]
    public class _15_10_7_5Fixture : Test262Fixture
    {
        public _15_10_7_5Fixture()
            : base("ch15\\15.10\\15.10.7\\15.10.7.5")
        {
        }

        [Test(Description = "RegExp.prototype.lastIndex is of type Number")]
        public void _15_10_7_5_1()
        {
            RunFile("15.10.7.5-1.js");
        }

        [Test(Description = "RegExp.prototype.lastIndex is a data property with specified attribute values")]
        public void _15_10_7_5_2()
        {
            RunFile("15.10.7.5-2.js");
        }

        [Test(Description = "Checking if enumerating the lastIndex property of RegExp instance fails")]
        public void S15_10_7_5_A8()
        {
            RunFile("S15.10.7.5_A8.js");
        }

        [Test(Description = "Checking if deleting the lastIndex property fails")]
        public void S15_10_7_5_A9()
        {
            RunFile("S15.10.7.5_A9.js");
        }
    }
}
