//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Ch09
{
    [TestFixture]
    public class _9_9Fixture : Test262Fixture
    {
        public _9_9Fixture()
            : base("ch09\\9.9")
        {
        }

        [Test(Description = "Trying to convert undefined to Object")]
        public void S9_9_A1()
        {
            RunFile("S9.9_A1.js");
        }

        [Test(Description = "Trying to convert null to Object")]
        public void S9_9_A2()
        {
            RunFile("S9.9_A2.js");
        }

        [Test(Description = "Trying to convert from Boolean to Object")]
        public void S9_9_A3()
        {
            RunFile("S9.9_A3.js");
        }

        [Test(Description = "Converting from various numbers to Object")]
        public void S9_9_A4()
        {
            RunFile("S9.9_A4.js");
        }

        [Test(Description = "Converting from various strings to Object")]
        public void S9_9_A5()
        {
            RunFile("S9.9_A5.js");
        }

        [Test(Description = "Converting from Objects to Object")]
        public void S9_9_A6()
        {
            RunFile("S9.9_A6.js");
        }
    }
}
