//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Ch08._8_12
{
    [TestFixture]
    public class _8_12_9Fixture : Test262Fixture
    {
        public _8_12_9Fixture()
            : base("ch08\\8.12\\8.12.9")
        {
        }

        [Test(Description = "Redefine a configurable data property to be an accessor property on a newly non-extensible object")]
        public void _8_12_9_9_b_i_1()
        {
            RunFile("8.12.9-9-b-i_1.js");
        }

        [Test(Description = "Redefine a configurable data property to be an accessor property on a newly non-extensible object")]
        public void _8_12_9_9_b_i_2()
        {
            RunFile("8.12.9-9-b-i_2.js");
        }

        [Test(Description = "Redefine a configurable accessor property to be a data property on a non-extensible object")]
        public void _8_12_9_9_c_i_1()
        {
            RunFile("8.12.9-9-c-i_1.js");
        }

        [Test(Description = "Redefine a configurable accessor property to be a data property on a non-extensible object")]
        public void _8_12_9_9_c_i_2()
        {
            RunFile("8.12.9-9-c-i_2.js");
        }
    }
}
