//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Ch15._15_4
{
    [TestFixture]
    public class _15_4_3Fixture : Test262Fixture
    {
        public _15_4_3Fixture()
            : base("ch15\\15.4\\15.4.3")
        {
        }

        [Test(Description = "Create new property of Function.prototype. When Array constructor has this property")]
        public void S15_4_3_A1_1_T1()
        {
            RunFile("S15.4.3_A1.1_T1.js");
        }

        [Test(Description = "Function.prototype.toString = Object.prototype.toString")]
        public void S15_4_3_A1_1_T2()
        {
            RunFile("S15.4.3_A1.1_T2.js");
        }

        [Test(Description = "Checking use isPrototypeOf")]
        public void S15_4_3_A1_1_T3()
        {
            RunFile("S15.4.3_A1.1_T3.js");
        }

        [Test(Description = "Checking use propertyIsEnumerable, for-in")]
        public void S15_4_3_A2_1()
        {
            RunFile("S15.4.3_A2.1.js");
        }

        [Test(Description = "Checking use hasOwnProperty, delete")]
        public void S15_4_3_A2_2()
        {
            RunFile("S15.4.3_A2.2.js");
        }

        [Test(Description = "Checking if varying the length property fails")]
        public void S15_4_3_A2_3()
        {
            RunFile("S15.4.3_A2.3.js");
        }

        [Test(Description = "Array.length === 1")]
        public void S15_4_3_A2_4()
        {
            RunFile("S15.4.3_A2.4.js");
        }
    }
}
